### ISSUE TITLE
NodeJS 8 support

### ISSUE THREAD

**Issue by guybedford** [spdy-http2/node-spdy#308]
Running the Node 8 nightly, I'm getting the following:

```
TypeError: this._renderHeaders is not a function
    at ServerResponse.writeHead (node_modules/spdy/lib/spdy/response.js:28:20)
    at ServerResponse._implicitHeader (_http_server.js:159:8)
    at ServerResponse.write (_http_outgoing.js:521:10)
    at ReadStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:1857:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:591:17)
```

I think `_renderHeaders` might be deprecated?

**Comment by MylesBorins** [comment]
I'm seeing things broken with the test suite with the landing on https://github.com/nodejs/node/pull/11926

did you get to the bottom of the renderHeaders problem? are there tests that cover that part of the api?
