### ISSUE TITLE
server_push Crash with fs.createReadStream.pipe()

### ISSUE THREAD

**Issue by yayo** [spdy-http2/node-spdy#318]
> assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at PriorityNode.removeChild (/tmp/cmbc/node_modules/spdy-transport/lib/spdy-transport/priority.js:72:3)
    at PriorityNode.remove (/tmp/cmbc/node_modules/spdy-transport/lib/spdy-transport/priority.js:61:15)
    at PriorityTree.add (/tmp/cmbc/node_modules/spdy-transport/lib/spdy-transport/priority.js:157:23)
    at PriorityTree.addDefault (/tmp/cmbc/node_modules/spdy-transport/lib/spdy-transport/priority.js:174:15)
    at Stream._initPriority (/tmp/cmbc/node_modules/spdy-transport/lib/spdy-transport/stream.js:97:27)
    at new Stream (/tmp/cmbc/node_modules/spdy-transport/lib/spdy-transport/stream.js:75:8)
    at Connection._createStream (/tmp/cmbc/node_modules/spdy-transport/lib/spdy-transport/connection.js:391:16)
    at Connection.pushPromise (/tmp/cmbc/node_modules/spdy-transport/lib/spdy-transport/connection.js:772:21)
    at Stream.pushPromise (/tmp/cmbc/node_modules/spdy-transport/lib/spdy-transport/stream.js:673:30)
    at ServerResponse.push (/tmp/cmbc/node_modules/spdy/lib/spdy/response.js:92:17)

>  function(req,res) {
  for(i=1;i<=51;i++)
   {var f="/"+i;
    var s=res.push(f,{request:{accept:'*/*'},response:{'content-type':'application/javascript'}});
    s.on('error',function(){});
    fs.createReadStream(process.argv[1],{autoClose:true}).pipe(s); /* CRASHED */
    //s.end(fs.readFileSync(process.argv[1])); /* OK */
   }
  res.end();
 }

refresh (F5) your browser quickly twice(or more), and it will crash !
may cause by exceed "transport.protocol.base.constants.MAX_PRIORITY_STREAMS"

**Comment by WVmf** [comment]
This is probably still the same issue as #285 and #244

**Comment by diasdavid** [comment]
Seems it is not happy when several push streams are being created and the connection drops half way through. 

@yayo could you try to convert this to a test?

**Comment by WVmf** [comment]
I'm also having the same issue as described here and in #244.

I.e. when using push I get an `AssertionError` after reloading the page a few times, or when the page has a sufficient amount of resources it also happens on the first page load.
But the issue doesn't seem to be caused by the push itself. Because the error happens after the pushed resource and some normal resources have already been delivered to the client. For example when only the first page load includes a pushed resource, the error still happens when subsequently loading different pages without any pushed resources. So the push only seems to trigger some condition that later on (after some additional requests) results in the error.

Output of "DEBUG=spdy:priority" up until assertion error:<details><summary>Click to expand</summary><p>
```
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=0 parent=-1 weight=1 exclusive=0
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=0 parent=-1 weight=1 exclusive=0
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=1 parent=0 weight=256 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=3 parent=0 weight=256 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority creating default node
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=2 parent=0 weight=16 exclusive=0
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=5 parent=3 weight=256 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=7 parent=5 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=9 parent=7 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=11 parent=9 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=13 parent=11 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=15 parent=13 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=17 parent=15 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=19 parent=17 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=21 parent=19 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=23 parent=21 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=25 parent=5 weight=183 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=2 parent=23 weight=110 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=27 parent=0 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=29 parent=0 weight=220 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=31 parent=0 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=33 parent=31 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=35 parent=33 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=37 parent=35 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=39 parent=0 weight=256 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=41 parent=37 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=43 parent=0 weight=220 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=45 parent=0 weight=256 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=47 parent=0 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=49 parent=47 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=51 parent=49 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=53 parent=51 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=55 parent=53 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=57 parent=55 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=59 parent=57 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=61 parent=59 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=63 parent=61 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=65 parent=63 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=67 parent=65 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=69 parent=67 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=71 parent=69 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=73 parent=71 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=75 parent=73 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=77 parent=75 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=79 parent=77 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=81 parent=79 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=83 parent=81 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=85 parent=83 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=87 parent=85 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=89 parent=87 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=91 parent=0 weight=220 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=93 parent=89 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=95 parent=93 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=97 parent=95 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=99 parent=97 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=101 parent=99 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=103 parent=101 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=105 parent=103 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=107 parent=105 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=109 parent=107 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=111 parent=109 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=113 parent=111 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=115 parent=113 weight=147 exclusive=1
Mon, 29 May 2017 11:51:38 GMT spdy:priority add node=117 parent=115 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=119 parent=0 weight=220 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=121 parent=0 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=123 parent=121 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=125 parent=123 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=127 parent=125 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=129 parent=127 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=131 parent=129 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=133 parent=131 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=135 parent=133 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=137 parent=135 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=139 parent=137 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=141 parent=139 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=143 parent=141 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=145 parent=143 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=147 parent=145 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=149 parent=147 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=151 parent=149 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=153 parent=151 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=155 parent=153 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=157 parent=155 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=159 parent=157 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=161 parent=159 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=163 parent=161 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=165 parent=163 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=167 parent=165 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=169 parent=167 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=171 parent=169 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=173 parent=171 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=175 parent=173 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=177 parent=175 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=179 parent=177 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=181 parent=179 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=183 parent=181 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=185 parent=183 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=187 parent=185 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=189 parent=187 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=191 parent=189 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=193 parent=191 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=195 parent=193 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=197 parent=195 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority hit maximum remove id=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=199 parent=197 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority hit maximum remove id=3
Mon, 29 May 2017 11:51:39 GMT spdy:priority add node=201 parent=199 weight=147 exclusive=1
Mon, 29 May 2017 11:51:39 GMT spdy:priority hit maximum remove id=2
```
</p></details>

`AssertionError` output:
```
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at PriorityNode.removeChild (d:\some\path\node_modules\spdy-transport\lib\spdy-transport\priority.js:72:3)
    at PriorityNode.remove (d:\some\path\node_modules\spdy-transport\lib\spdy-transport\priority.js:61:15)
    at PriorityTree.add (d:\some\path\node_modules\spdy-transport\lib\spdy-transport\priority.js:157:23)
    at Stream._initPriority (d:\some\path\node_modules\spdy-transport\lib\spdy-transport\stream.js:101:25)
    at new Stream (d:\some\path\node_modules\spdy-transport\lib\spdy-transport\stream.js:75:8)
    at Connection._createStream (d:\some\path\node_modules\spdy-transport\lib\spdy-transport\connection.js:391:16)
    at Connection._handleHeaders (d:\some\path\node_modules\spdy-transport\lib\spdy-transport\connection.js:438:21)
    at Connection._handleFrame (d:\some\path\node_modules\spdy-transport\lib\spdy-transport\connection.js:321:10)
    at Parser.<anonymous> (d:\some\path\node_modules\spdy-transport\lib\spdy-transport\connection.js:158:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at readableAddChunk (d:\some\path\node_modules\readable-stream\lib\_stream_readable.js:212:18)
    at Parser.Readable.push (d:\some\path\node_modules\readable-stream\lib\_stream_readable.js:171:10)
    at Parser.Transform.push (d:\some\path\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at next (d:\some\path\node_modules\spdy-transport\lib\spdy-transport\protocol\base\parser.js:52:12)
    at d:\some\path\node_modules\spdy-transport\lib\spdy-transport\protocol\http2\parser.js:71:5
```

My push related code:
```javascript
let pushedStream = res.push(pushResrcPath, {
    status: 200,
    method: "GET",
    request: {
        accept: "*/*"
    },
    response: {
        "content-type": mime.lookup(pushResrcPath)
    }
});
pushedStream.on("error", (err) => { console.error("Push stream failed", err); });
pushedStream.on("finish", () => { console.log("Push stream finished."); });
let fileStream = fs.createReadStream(path.resolve(__dirname, path.join("../path/to/public/", pushResrcPath.replace(/^\/someprefix/i, ""))));
fileStream.pipe(pushedStream);
```
`npm ls` output for spdy:
```
+-- spdy@3.4.4
| +-- handle-thing@1.2.5
| +-- http-deceiver@1.2.7
| +-- select-hose@2.0.0
| `-- spdy-transport@2.0.18
|   +-- hpack.js@2.1.6
|   +-- obuf@1.1.1
|   `-- wbuf@1.7.2
|     `-- minimalistic-assert@1.0.0
```
FWIW: I'm using Node.js v6.9.1 in combination with Express v4.15.2 on Windows 10.

**Comment by matthewp** [comment]
@diasdavid I've recreated the @yayo example as a gist here: https://gist.github.com/matthewp/d5a26ba620fc921754f3ba4892a9b230

I tried to make it into a test but I was not successful. I think I don't understand the lower-level apis well enough yet. Is there a similar test that I could use as an example?  

Either way, what's the best way to debug this. Currently a bit of a blocker for me.

**Comment by matthewp** [comment]
An update on what is going on here.  The issue is in spdy-transport.

1. spdy-transport has a `maxCount` option, and when that goes over it removes the first node in the tree: https://github.com/spdy-http2/spdy-transport/blob/0438165a1e08b4b72dd803721698f5b7c4545c21/lib/spdy-transport/priority.js#L161
2. When there is a priority frame the first node also gets removed.

Since the node was removed in (1) it fails in (2). I'm not sure what the proper solution is here @diasdavid @indutny.  Should `_handlePriority` check if the node is still in the tree before calling remove() or is there some other approach here?

**Comment by matthewp** [comment]
The root problem is that [_removeNode](https://github.com/spdy-http2/spdy-transport/blob/0438165a1e08b4b72dd803721698f5b7c4545c21/lib/spdy-transport/priority.js#L184) removes the node from the `map` but not the `list`. Fixing that ensures that it is removed from the tree. This also fixes a memory leak.

**Comment by matthewp** [comment]
PR: https://github.com/spdy-http2/spdy-transport/pull/48

**Comment by veaba** [comment]
![qq 20180913020657](https://user-images.githubusercontent.com/8652596/45444323-c3a0b000-b6f9-11e8-9219-b0000af4cac1.png)

before
```scripts
"backpack-dev":"cross-env NODE_RENDER=backpackDev NODE_ENV=development backpack debug dev"
```
after
```scripts
cross-env NODE_RENDER=backpackDev NODE_ENV=development backpack dev
```
I just removed `debug` string，when I refresh frequently pages,it is work 。

T_T
