### ISSUE TITLE
"Stream write aborted"

### ISSUE THREAD

**Issue by samkuhn** [spdy-http2/node-spdy#322]
I'm getting errors in the console whenever I stop playback of a HTML5 video, or change page while one is playing over h2:

```bash
  Error: Stream write aborted
      at /Users/sam/project/ut-utile-newbackend/node_modules/spdy-transport/lib/spdy-transport/stream.js:141:16
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

Is this normal? It doesn't seem to hurt (but is a tad annoying) Is there a way to silence them?

**Comment by virginielgb** [comment]
I have the same error, it's pretty annoying as I have to handle multiple connections and it keeps crashing...

**Comment by wmbutler** [comment]
Did either of you come up with a solution to this? We are seeing these as well.

**Comment by OcelotJungle** [comment]
Same error. Anything resolved?

**Comment by RezaErfani67** [comment]
Same error. Anything resolved?

**Comment by RezaErfani67** [comment]
I got the same error...
