### ISSUE TITLE
AssertionError on production

### ISSUE THREAD

**Issue by th3nate** [spdy-http2/node-spdy#336]
hello,
im getting a lot of assertion error messages on my production server.
the server is a simple API running over express, with no push functions or anything.

here's the stack trace:

`AssertionError [ERR_ASSERTION]: false == true
    at PriorityNode.removeChild (/app/node_modules/spdy-transport/lib/spdy-transport/priority.js:74:3)
    at PriorityNode.remove (/app/node_modules/spdy-transport/lib/spdy-transport/priority.js:62:15)
    at Stream._handlePriority (/app/node_modules/spdy-transport/lib/spdy-transport/stream.js:305:18)
    at Stream._handleFrame (/app/node_modules/spdy-transport/lib/spdy-transport/stream.js:128:10)
    at Connection._handleFrame (/app/node_modules/spdy-transport/lib/spdy-transport/connection.js:324:12)
    at Parser. (/app/node_modules/spdy-transport/lib/spdy-transport/connection.js:156:10)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at Parser.Readable.push (/app/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at Parser.Transform.push (/app/node_modules/readable-stream/lib/_stream_transform.js:146:32)
    at next (/app/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:53:12)
    at /app/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:72:5
    at Parser.onPriorityFrame (/app/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:539:3)
    at Parser.onFrameBody (/app/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:154:10)`

any ideas would be much appreciated.
Thanks!

**Comment by wmertens** [comment]
This is better tracked in https://github.com/spdy-http2/spdy-transport/issues/47
