### ISSUE TITLE
Exception while processing request

### ISSUE THREAD

**Issue by luisfilsilva** [spdy-http2/node-spdy#386]
Hi guys,

I'm getting this exception when receiving a HTTP2 request:

internal/buffer.js:945
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:945:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:185:19)
    at Stream.<anonymous> (/notification-listener/node_modules/handle-thing/lib/handle.js:88:10)
    at Stream.emit (events.js:327:22)
    at endReadableNT (/notification-listener/node_modules/readable-stream/lib/_stream_readable.js:1094:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Any clue about this? I can share the http2 wireshark trace

Many Thanks!!!
Luís

**Comment by luisfilsilva** [comment]
Closing, since this has already been reported before
