### ISSUE TITLE
[DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by khteh** [spdy-http2/node-spdy#390]
Bump into the following deprecation warning in the following code snippet:
```
healthchecks.get('/live', function (req, res, next) {
  res.send('OK')
});
```
```
[nodejsrestapi-1] (node:1) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated 
[nodejsrestapi-1]     at ServerResponse.writeHead (/app/node_modules/spdy/lib/spdy/response.js:18:12) 
[nodejsrestapi-1]     at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:44:26) 
[nodejsrestapi-1]     at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:44:26) 
[nodejsrestapi-1]     at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:44:26) 
[nodejsrestapi-1]     at ServerResponse._implicitHeader (node:_http_server:287:8) 
[nodejsrestapi-1]     at ServerResponse.end (/app/node_modules/compression/index.js:103:14) 
[nodejsrestapi-1]     at ServerResponse.send (/app/node_modules/express/lib/response.js:232:10) 
[nodejsrestapi-1]     at file:///app/src/webapi/routes/healthchecks.js:23:9 
[nodejsrestapi-1]     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) 
[nodejsrestapi-1]     at next (/app/node_modules/express/lib/router/route.js:144:13)
```
`"spdy": "^4.0.2"`
`"express": "^4.18.1",`
Node: v18.7.0
https://github.com/expressjs/express/issues/4976

**Comment by eddie-liu-avepoint** [comment]
same issue
